@echo off
echo Installing dependencies...
pip install -r requirements.txt

echo Copying data...
py setup_data.py

echo Training model...
py train_model.py

echo Running Dashboard...
streamlit run app.py
